### ISSUE TITLE
Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by xfreezy22** [Tiramitzu/discord-chat-mirror#1]
Hello, first thank you for your work and the script, unfortunately I have problems running this and always get the error: 

```
internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\Administrator\discord-chat-mirror\selfbot-ver\app.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-chat-mirror@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-chat-mirror@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2022-08-07T09_09_04_751Z-debug.log
```

any solution for this ?

**Comment by Tiramitzu** [comment]
Hi, thank you for opening an issue, is this your first time running the code? If it is, mind checking the `package.json` for me and make sure `"type": "module",` is there

**Comment by xfreezy22** [comment]
thanks for the fast answer.
yes it the first time.

heres the whole package.json

```
{
	"name": "discord-chat-mirror",
	"version": "1.0.0",
	"description": "Track/Mirror/Log Discord Channel Messages",
	"main": "app.js",
	"type": "module",
	"scripts": {
		"start": "node ."
	},
	"author": "Tiramitzu",
	"license": "MIT",
	"dependencies": {
		"discord.js": "^13.6.0",
		"dotenv": "^16.0.0",
		"selfcore": "^1.1.1"
	}
}

```

**Comment by Tiramitzu** [comment]
Hey, sorry I can't reproduce this, I've tried it again and again, but it just works without any problem, yes I start it fresh without anything modified except `.env`. Please do tell me if you found where the problem is, thank you.

**Comment by xfreezy22** [comment]
may i ask which node-fetch version you are using ?

**Comment by Tiramitzu** [comment]
I don't use node-fetch, I'm using `git clone` and if you're asking for NodeJS version, its `16.16.0` LTS

**Comment by xfreezy22** [comment]
thanks. that info helped. working now
is there a way to monitor multiple channel at once with your script?

**Comment by Tiramitzu** [comment]
>is there a way to monitor multiple channel at once with your script?

If there is, its probably gonna be a paid version, sorry

**Comment by xfreezy22** [comment]
i sent you an mail.

**Comment by Tiramitzu** [comment]
I've replied to you yesterday btw if you haven't notice yet. I'm more onto discord than email (I rarely open it). Tiramitzu#2853
