### ISSUE TITLE
Not working on some channels...

### ISSUE THREAD

**Issue by koctalha** [Tiramitzu/discord-chat-mirror#15]
**Describe the bug**
Hi Tiramitzu, 
Thank you for this btw. I believe, It's working well on much smaller channels. But, whenever when I try to mirror messages from bigger channel, it's not working. Let me give you an example the channel below. Do you have any idea for this? Are some channel owners able to prevent this mirrorring? How can we get over it? 

**To Reproduce**
You can try this channel:
https://discord.com/channels/232457884867362816/232457884867362816

**Comment by Tiramitzu** [comment]
Fixed in https://github.com/Tiramitzu/discord-chat-mirror/commit/8b02aa34eea38ee0d6d2e689adcdab4d82d3175c
